---

- hosts: Ubuntu
  become: true
  remote_user: admin-server
  tasks:
    - name: Copy Files to Ubuntu Server
      copy: src=files/check-mk-agent_2.1.0p18-1_all.deb dest=/home/admin-server/Transfer/
