---

- hosts: Proxmox_BS:Proxmox_VE
  become: true
  remote_user: root
  tasks:
    - name: update repository index
      apt:
        update_cache: yes
    - name: upgrade proxmox server
      apt:
        upgrade: dist
