---

- hosts: Proxmox_BS:Proxmox_VE
  become: true
  remote_user: root
  tasks:
    - name: Copy Files to Proxmox Systems
      copy: src=files/check-mk-agent_2.4.0p8-1_all.deb dest=/root/Install/
    - name: Update CheckMK Agent
      command: apt install /root/Install/check-mk-agent_2.4.0p8-1_all.deb -y --allow-downgrades
